### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by ravimittal84** [thomaslevesque/AutoRunCustomTool#11]
My .tt file is in the root folder of the project and when I assign template.tt to my controller methods in Controller folder, it gives an error saying -
Error: Target item c:\...\ProjectFolder\Controllers\template.tt was not found.

The template file is in C:\...\ProjectFolder\template.tt

I tried giving ~\template.tt and ..\template.tt but it did not help. 

The last thing I would want to do would be to give the full path. That would mean I need to change the path everytime I clone it on another machine.

**Comment by ravimittal84** [comment]
../template.tt worked.

**Comment by thomaslevesque** [comment]
Hi,

Just tried it in a new ASP.NET MVC project, and I didn't reproduce the issue. I added `..\template.tt` in the _Run custom tool on_ property of a controller class, and the T4 template is correctly re-executed when the controller class changes.

Is there anything special about your project? Perhaps some files are included in the project as links?

**Comment by thomaslevesque** [comment]
Looks like we posted at the same time. Glad it worked for you!

**Comment by ravimittal84** [comment]
Haha. I beat you to it :)

Having to run custom tool for any change was really annoying. 

Many thanks for this tool, it works great!
