### ISSUE TITLE
Support for VS 2017

### ISSUE THREAD

**Issue by jakubbukaj** [thomaslevesque/AutoRunCustomTool#12]
Hello,
do you plan to support VS 2017?

Thanks for great tool

**Comment by thomaslevesque** [comment]
Hi @jakubbukaj,

Yes, I intend to support VS2017, but I haven't looked into it yet. Thanks for reminding me!

**Comment by thomaslevesque** [comment]
I just released version 2.1.0, which supports VS2017.
