### ISSUE TITLE
Error when loading plugin in VS2013

### ISSUE THREAD

**Issue by ZlotZ** [thomaslevesque/AutoRunCustomTool#14]
Hi. 

After insalling the AutoRunCustomTool v2.1.0 on my VS 2013, when I first opened a solution, I got the error:

![image](https://cloud.githubusercontent.com/assets/9023099/21899841/ebc1b99a-d8d8-11e6-8066-698040ed6485.png)

In ActivityLog.xml there's that:

  <entry>
    <record>322</record>
    <time>2017/01/12 17:07:53.109</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [AutoRunCustomToolPackage]</description>
    <guid>{7EC0F89C-F00D-48AB-A76B-713D90FDBF03}</guid>
  </entry>
  <entry>
    <record>323</record>
    <time>2017/01/12 17:07:53.119</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [AutoRunCustomToolPackage]</description>
    <guid>{7EC0F89C-F00D-48AB-A76B-713D90FDBF03}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.</errorinfo>
  </entry>
  <entry>
    <record>324</record>
    <time>2017/01/12 17:07:53.119</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [AutoRunCustomToolPackage]</description>
    <guid>{7EC0F89C-F00D-48AB-A76B-713D90FDBF03}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.</errorinfo>
  </entry>

Is it an issue? Is it mandatory to install this missing "Microsoft.VisualStudio.Shell.11.0"?
Can you fix the tool for it to be independent of this?

Thank you!

**Comment by thomaslevesque** [comment]
Ah, that must be a result of my latest update to make it compatible with VS2017... I checked that it still worked in VS2015, but I don't have earlier VS versions installed on my machine. I'll look into it ASAP.

**Comment by ZlotZ** [comment]
Thank you very much. I'd really appreciate it, and I look forward to being able to use your tool in my project. Thanks!


Eduardo

________________________________

**Comment by ZlotZ** [comment]
Hi, thank you very much, it loaded fine, and I can see the "Run custom tool on" on the file properties.

Thank you, you are helping a lot of people with your solution!

**Comment by thomaslevesque** [comment]
Hi @ZlotZ, thanks for confirming that it works, I'll release it on the VS marketplace now.
