### ISSUE TITLE
Crashes a lot in the latest visual studio

### ISSUE THREAD

**Issue by ZuechB** [thomaslevesque/AutoRunCustomTool#20]
I am using the latest visual studio enterprise edition and while saving in cshtml files this tool kills visual studio and display the following error after reboot. This happens at random within the day almost everyday.

![capture](https://user-images.githubusercontent.com/1290658/38052525-872a6456-329f-11e8-9c39-d375a0986a13.PNG)

**Comment by thomaslevesque** [comment]
Hi @ZuechB,

Are you using VS 2017 v15.6.4?
Do you have any logs for the crash?
I'll look into it when I can, but probably not in the next few days

**Comment by thomaslevesque** [comment]
> Are you using VS 2017 v15.6.4?
> Do you have any logs for the crash?

Hi @ZuechB,

The information above would be useful to solve the problem.

BTW, did you enable AutoRunCustomTool for these cshtml files?
