### ISSUE TITLE
Download link still gets version 2.2, not version 3

### ISSUE THREAD

**Issue by blodgettb** [thomaslevesque/AutoRunCustomTool#24]
I got version 3 to work by: get the source code, "Remove and Sort Usings", rebuild all, quit VS2019, and run AutoRunCustomTool\bin\Debug\AutoRunCustomTool.vsix which was just built.

**Comment by thomaslevesque** [comment]
Hi @blodgettb, alternatively, you can just get it [from the Visual Studio Gallery](https://marketplace.visualstudio.com/items?itemName=ThomasLevesque.AutoRunCustomTool) :wink:

I forgot to update the Github Releases, sorry about that. I'll update them now.

> "Remove and Sort Usings"

Why?

**Comment by st3inn** [comment]
I am still getting version 2.2.0 when downloading from [marketplace](https://marketplace.visualstudio.com/items?itemName=ThomasLevesque.AutoRunCustomTool&ssr=false#overview)

**Comment by thomaslevesque** [comment]
Ah, I see. Not sure what happened here. I'll look into it.

**Comment by thomaslevesque** [comment]
Well, it looks like I pushed the wrong file. I'm not sure how it's possible, since the gallery shows version 3.0.0, and this information is extracted from the uploaded VSIX. I'll try to push a 3.0.1, hopefully it will work as expected this time.

**Comment by st3inn** [comment]
Works :) 
I saw it under Updates in Manage Extensions in VS, but got an error after closing VS that it was already installed, Marketplace download also just offered to install for older VS versions.
Had to uninstall from VS, then download and install. VS shows version 3.0.1 installed

**Comment by thomaslevesque** [comment]
Version 3.0.1 fixes the problem.
