### ISSUE TITLE
A lazy and easy way to Auto Run the Custom Tool on own file

### ISSUE THREAD

**Issue by HClausing** [thomaslevesque/AutoRunCustomTool#25]
Maybe a bool property on own Project item to execute the custom tool on the same file when it gets modified.

**Comment by thomaslevesque** [comment]
Hi @HClausing,
I'm not sure I understand your suggestion. Could you elaborate?

**Comment by HClausing** [comment]
Hi @thomaslevesque , how are you?

For example, we have a Project item named "Person.efmodel". It's a XML file that opens on external exe for editing properties  (On past versions of Visual Studio, was a custom designer inside VS, but I have no time to port it to VS2017). It had one dependant file: Person.designer.cs: An auto generated class based on properties' list edited on efmodel file editor) .

The custom tool to re-generate Person.designer.cs properties from xml is set Person.efmodel Project item (the same file that will be modified on external app save command).

By this way, a suggest a new property item for you AutoRunCustomTool for Project item: A check box to run the custom tool on the same file, instead of editing a list of target file, to set the same file.

Something like this:

![image](https://user-images.githubusercontent.com/15158923/57849828-b40ac700-77b2-11e9-8020-276cfae47fae.png)

It's just a suggestion. Thanks for the attention.

**Comment by thomaslevesque** [comment]
Hi @HClausing,

But you don't need AutoRunCustomTool in this scenario... If a project item has a custom tool and you modify it, Visual Studio already runs the custom tool on it. AutoRunCustomTool is only useful to run a custom tool on a different file than the one that is modified.

**Comment by HClausing** [comment]
Hi!

Actually, it's not running the custom tool automatically because the efmodel file is modified by external application outside VS.

Is there any config on VS to change this scenario?

Thanks.

**Comment by thomaslevesque** [comment]
> Actually, it's not running the custom tool automatically because the efmodel file is modified by external application outside VS.

In this case, AutoRunCustomTool won't help you... It triggers the custom tool based on a Visual Studio event when the file is saved. It doesn't actually watch the file for changes (although there's an open issue to implement this: https://github.com/thomaslevesque/AutoRunCustomTool/issues/17)

> Is there any config on VS to change this scenario?

Not that I know of. You'd have to open the efmodel file in Visual Studio and save it.

**Comment by HClausing** [comment]
Right, no problems at all.

Thanks, and congratulations for this nice tool!
