### ISSUE TITLE
Define watched files with globs

### ISSUE THREAD

**Issue by jods4** [thomaslevesque/AutoRunCustomTool#26]
Could you make this work from globs, maybe in some csproj properties or another config file?

We generate code for a lot of files in our projects (e.g. all *.cs files in a specific folder) so remembering to set custom properties every time we add one isn't the best experience.

**Comment by thomaslevesque** [comment]
Hi @jods4,

Thanks for the suggestion!

In fact, I think it's already possible. If your "trigger" files are in the folder Data, you can do something like this:

```xml
<None Update="Data/**">
    <RunCustomToolOn>Target.tt</RunCustomToolOn>
</None>
```

(replace `None` with the actual build action of the trigger files)

I haven't tried it, but I think it *should* work...

**Comment by jods4** [comment]
@thomaslevesque Thanks, will try! Awesome that it may already work.

**Comment by jods4** [comment]
Guess what? it works!
This is fantastic. Now any time I add/remove/modify a file my generated code is automatically updated.

Thanks a lot. 
This extension is gold, I don't know why VS can't run tools automatically when you modify some files.

**Comment by thomaslevesque** [comment]
Glad it worked for you!

> Caveat: the custom tool path seems to be relative to the file that triggers it. So better prefix that path with `$(ProjectDir)`.

Yes, it's relative to the trigger file
