### ISSUE TITLE
Custom Tool in different project than trigger files

### ISSUE THREAD

**Issue by xMANIGHTx** [thomaslevesque/AutoRunCustomTool#27]
I was so happy today when I discovered your great snippet... but then after install and configuration I realized that maybe I couldn't use it...
I have a web application with the .resx files and my own T4 template in class project (in the same solution of the web application of course). I don't know if there is already a way to have the .resx files reference the tool which is in another project.
This is a common scenario with the web application referencing a "core" class where all the settings, helpers, managers and models are.
If this is not possible, maybe a "..." to search for the file in the project or something instead of just the tool name?

Also will this trigger even if I update the .resx files from outside visualstudio? I saw you added this request to enanchment but didn't understand if is already active.

Please this is one of those little things that really change the way you work and help make big things!
Maybe add a donation button for supporters, but don't drop support on this little nasty helper! I'm sure many out there will be happy of any addition!

**Comment by thomaslevesque** [comment]
Hi @xMANIGHTx,

Having the T4 and resx in different projects should work, using a relative path (`../OtherProject/T4template.tt`). See [this other issue](https://github.com/thomaslevesque/AutoRunCustomTool/issues/27).

> Also will this trigger even if I update the .resx files from outside visualstudio? I saw you added this request to enanchment but didn't understand if is already active.

This isn't done yet. To be honest, I haven't really worked on this project in a long time... Contributions are welcome.

> Please this is one of those little things that really change the way you work and help make big things!
> Maybe add a donation button for supporters, but don't drop support on this little nasty helper! I'm sure many out there will be happy of any addition!

Thanks for the kind words!
I tried a donation button before, on a project much more popular than this one, and I got very few donations (although the few I got were quite generous). But anyway, money isn't what motivates me to work on OSS projects. I mostly do this for fun; if I receive money, I feel compelled to address issues users are having, and then it feels like work and isn't fun anymore...
