### ISSUE TITLE
Just installed into VS2017

### ISSUE THREAD

**Issue by ManlyBoy** [thomaslevesque/AutoRunCustomTool#28]
How's this supposed to work.
I've installed it OK in VS2017but it's not appearing in my Properties window as per the screen captures. Same problem in VS2019.
**Edit:**
It doesn't recognize/work for shared projects available in VS2015 and greater.

**Comment by thomaslevesque** [comment]
Hi @ManlyBoy,

What kind of project is this? SDK-style project (e.g. .NET Core, .NET Standard) or "old-school" project?
Unfortunately AutoRunCustomTool doesn't work on SDK-style projects (see #18), and I don't know how to fix it...

**Comment by ManlyBoy** [comment]
Hi,

[Shared projects](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/shared-projects?tabs=windows) (only available since VS2015) are agnostic and are intended to work on all types. Shared project's code is not compiled at all except by their owning project.
