### ISSUE TITLE
Can't figure out how to use it

### ISSUE THREAD

**Issue by Buzzker** [thomaslevesque/AutoRunCustomTool#34]
A sample would be nice.
I want to cut my CHANGELOG.md to 500 symbols so my TFS Pipeline grabs it (because Android Play Store allows changelogs of max 500 symbols.
But I don't get the "Targets" array displayed on my trigger file.

![image](https://user-images.githubusercontent.com/7758237/157096406-8a9afe60-6d99-43f6-a193-f8ae2c676856.png)

**Comment by thomaslevesque** [comment]
Hi Buzzker,

> A sample would be nice.

There's a sample in the README. Suggestions on how to improve it are welcome!

> But I don't get the "Targets" array displayed on my trigger file.

What kind of project is it? I believe you might be running into #18. If it is the case, you can specify the target files as described in the [last comment](https://github.com/thomaslevesque/AutoRunCustomTool/issues/18#issuecomment-1053609437).

**Comment by thomaslevesque** [comment]
> Regarding sample: a folder "samples" in the source code with sample solutions (e.g. the one from screenshots) would be nice.

Good idea!

> My project is .Net Standard

OK, so it's a SDK-style project (with a `<Project Sdk="...">` root element). It's a known issue, for which I unfortunately don't have a fix. As mentioned before, even though the property doesn't show up in the UI, you can still [set it directly in the project file](https://github.com/thomaslevesque/AutoRunCustomTool/issues/18#issuecomment-1053609437), and it should work as expected.

**Comment by thomaslevesque** [comment]
I added two sample projects ("classic" and "SDK-style"), and a README for each.
I hope this helps, thanks for the suggestion!
