### ISSUE TITLE
Version 2022 cannot be found

### ISSUE THREAD

**Issue by dconsavi** [thomaslevesque/AutoRunCustomTool#35]
Hello,
I'm trying to find the 2022 version of your tool but when I clicked on the link in the readme (https://marketplace.visualstudio.com/items?itemName=ThomasLevesque.AutoRunCustomTool2022) I come across a not found page on the marketplace website.
![image](https://user-images.githubusercontent.com/85500727/157230283-25dc9a43-b502-49f9-a050-e6a12ee3d2e1.png)
So I tried searching directly in the marketplace but only found the version < 2022.

**Comment by thomaslevesque** [comment]
It seems to be working for me... However it's asking me to login, which is weird. Even in private browsing, I can't see a 404 page; I'm always requested to login. I'll look into it.

**Comment by thomaslevesque** [comment]
Dumb mistake on my part: it wasn't publicly listed. I didn't realize I had to do this explicitly when I published it. It should work now, thanks for reporting this!
