### ISSUE TITLE
Run T4 Template in another project

### ISSUE THREAD

**Issue by inforithmics** [thomaslevesque/AutoRunCustomTool#7]
Running a T4 Template from another project doesn't work because it only searches the current project for T4 Templates.

**Comment by xMANIGHTx** [comment]
I have this structure:
Project With Space in Name A (this is a class project)
-- Localization
-- -- Res.tt
Project With Space In Name B (this is a web application project)
-- AppGlobalResources
-- -- Application.resx

On Application.resx properties I put:
..\..\Project With Space in Name A\Localization\Res.tt

I tried opening Application.resx inside VS, adding a couple of lines and saving, but it seems Auto Run Custom Tool is not triggered... I don't even have anything in the output window (not even errors) and AutoRunCustomTool is selected in output window.

Any hint? Thanks
